Added vscode configurations for the workspace
near-projects/wallet-selector pull request #123
Opened 2022-02-09 17:05 UTC by rgolea

closes #110

Please let me know if you would remove some of them or allow them all. Also, there is still a need for other editors as well.

2022-02-10 08:14 UTC, lewis-sqa commented
Added @amirsaran3 & @kujtimprenkuSQA as reviewers. I don't use VS Code enough to understand what plugins are valid other than ESLint. The most important thing to me is Prettier is disabled (in favor of ESLint) as per https://github.com/near-projects/wallet-selector#editor-setup

2022-02-10 09:23 UTC, kujtimprenkuSQA approved these changes

2022-02-10 10:10 UTC, rgolea commented
Yes, I don't use WebStorm. I'm pretty sure there are configs for each editor we use. Please add the similar configs as best as possible. Maybe add your own editor configurations @lewis-sqa ?

The recommended extensions are just that: recomendations and that can be arbitrary but the configs aren't and disabling prettier from the start is important.

2022-02-10 14:14 UTC, lewis-sqa requested changes

2022-02-10 14:14 UTC, lewis-sqa commented on .vscode/extensions.json
> +    "syler.sass-indented"
Maybe we need ESLint on these files too... Just kidding. Could we format this file correctly though. I think we have a mixture of tabs and spaces!

2022-02-16 16:38 UTC, lewis-sqa approved these changes

2022-02-16 17:51 UTC, merged