Task 65/fix near wallet signing with attached near
near-projects/wallet-selector pull request #71
Opened 2022-01-25 09:06 UTC by amirsaran3

2022-01-25 12:26 UTC, GentBinakuSQA approved these changes

2022-01-25 12:26 UTC, kujtimprenkuSQA approved these changes

2022-01-26 02:26 UTC, mikedotexe approved these changes

2022-01-26 07:12 UTC, lewis-sqa requested changes
Looks like there's very similar changes here to #70. Can we address the comments there first. Should hopefully isolate what exactly this PR has changed in comparison too.

2022-01-27 01:02 UTC, mikedotexe commented
> Looks like there's very similar changes here to #70. Can we address the comments there first. Should hopefully isolate what exactly this PR has changed in comparison too.

you're right, that other PR also solves that issue for me regarding needing a redirect to Wallet when attaching some NEAR

2022-01-31 10:47 UTC, lewis-sqa approved these changes

2022-01-31 10:49 UTC, merged