First Commit
near-projects/wallet-selector pull request #84
Opened 2022-01-27 13:44 UTC by GentBinakuSQA

2022-01-27 16:26 UTC, lewis-sqa commented
I know this is still in draft, but we should look to create a separate PR to address the formatting issues that ESLint has detected. It makes it easy to review that way. As mentioned in the task, we'll want to time the formatting changes with the team to avoid triggering excessive Git conflicts.

2022-01-28 13:37 UTC, GentBinakuSQA commented
@lewis-sqa 
https://github.com/near-projects/wallet-selector/blob/7e51d458d80d4572f6648cd9da9a735b621a7511/package.json#L12

2022-01-28 14:49 UTC, lewis-sqa requested changes

2022-01-28 14:49 UTC, lewis-sqa commented on package.json
> +  },
We don't need this configuration as ESLint will use the dedicated file

2022-01-28 14:49 UTC, lewis-sqa commented on package.json
> +    "npm": "^8.4.0",
We can remove this dependency as this supplied with Node.js itself and considered a prerequisite for this project.

2022-01-28 14:49 UTC, lewis-sqa commented on README.md
> +<<<<<<< HEAD
It looks like some conflicts are still present here. As mentioned previously however, changes from `npm run lint:fix` should be done as part of another PR. The goal of this PR is just to enable ESLint without impacting the entire codebase

2022-02-04 09:36 UTC, lewis-sqa commented
Superseded by #105.

2022-02-04 09:36 UTC, closed without merging